Pylint 2.15.7 Fix
Tested on Python 3.10 an error occurs, because pylint now expands files to a dictionary:

  File "/usr/local/lib/python3.10/site-packages/pylint/lint/pylinter.py", line 874, in _iterate_file_descrs
    for descr in self._expand_files(files_or_modules).values():
  File "/usr/local/lib/python3.10/site-packages/prospector/tools/pylint/linter.py", line 24, in _expand_files
    if self._files.check_module(module["path"]):
TypeError: string indices must be integers

with the proposed change this is considered