Add missing code on mypy errors
Use mypy api to get the messages details

before:
```
prospector/blender.py:81:13: error(mypy): List comprehension has incompatible type List[Message]; expected List[str]  [misc]
prospector/blender.py:101:12: error(mypy): Incompatible return value type (got "list[str]", expected "list[Message]")  [return-value]
```

after:
```
prospector/blender.py:81:12: misc(mypy): List comprehension has incompatible type List[Message]; expected List[str].
prospector/blender.py:101:11: return-value(mypy): Incompatible return value type (got "list[str]", expected "list[Message]").
```